### PR TITLE
Fix #42: PHP 8.2 Creation of dynamic property in TTFontFile.php (part2)

### LINKED ISSUE #42: php8.2: Creation of dynamic property tFPDF\TTFontFile::$maxUniChar is deprecated
At least (private?) properties `$maxUniChar` and `$glyphdata` are not defined within class `TTFontFile`

### PR DESCRIPTION
**Pull request by mathroc**
I think I got all occurences, this was done with:

`diff <(rg 'private \$.*;' vendor/docnet/tfpdf/src/tFPDF/TTFontFile.php | sed 's/.*\$\([^; ]*\)[; ].*/\1/' | sort | uniq) <(rg 'this->[a-zA-Z0-9_]+[^(a-zA-Z0-9_]' vendor/docnet/tfpdf/src/tFPDF/TTFontFile.php  | sed 's/.*this->\([a-zA-Z0-9_]*\)[^a-zA-Z0-9_(].*/\1/' | sort | uniq)`

### CODE REVIEW

**Review by kazsaj — APPROVED** [review]

**Comment by kazsaj** [comment]
Thank you for the PR. You're changes are included in the 2.2.7 release:
https://github.com/DocnetUK/tfpdf/releases/tag/v2.2.7

**Comment by mathroc** [comment]
thank you for the quick release!

**Comment by mathroc** [comment]
Is there a manual action needed for the release to appear on packagist?

**Comment by BafS** [comment]
image

Done. There is a link on packagist to do it

**Pull request merged**
