### PR TITLE
Fixed bug when thickness and position of line for underline text not …

### PR DESCRIPTION
**Pull request by PulsarV**
…changing.

### CODE REVIEW

**Comment by kazsaj** [comment]
Hello @PulsarV 

Thanks for the PR, it indeed looks like a bug from your changes. But would you be able to prepare a small snippet where I could test the change in behaviour before and after the changes?

I mean something like this:
```php
$pdfLibrary = new tFPDF\PDF();
$pdfLibrary->AddPage();
$pdfLibrary->Write(5, "Test text");
$pdfLibrary->Ln(10);
$pdfLibrary->SetFont('Arial', 'U', 14);
$pdfLibrary->Write(5, "Underscore test text");
$pdfLibrary->Ln(10);
$pdfLibrary->SetFont('Arial', '', 14);
$pdfLibrary->Write(5, "Regular test text");
echo $pdfLibrary->output();
```

Unless that's exactly what I should test it with.

Thanks,
Kaz

**Comment by PulsarV** [comment]
I must add this code to the repository, or a comment?

**Comment by kazsaj** [comment]
A comment (to this PR) will be enough, I will try to make a unit test based on it later.

**Comment by PulsarV** [comment]
$pdfLibrary = new PDF();
        $pdfLibrary->AddFont('DejaVuSerif', '', 'DejaVuSerif.ttf', true);
        $pdfLibrary->AddPage();
        $pdfLibrary->Write(5, "Test text");
        $pdfLibrary->Ln(10);
        $pdfLibrary->SetFont('DejaVuSerif', 'U', 14);
        $pdfLibrary->Write(5, "Underscore test text");
        $pdfLibrary->Ln(10);
        $pdfLibrary->SetFont('DejaVuSerif', '', 14);
        $pdfLibrary->Write(5, "Regular test text");
        $result = $pdfLibrary->output();

**Comment by PulsarV** [comment]
I copied DejaVuSerif.ttf to folder %FPDF_FONTPATH%/unifont before.

**Comment by kazsaj** [comment]
Thanks, I was able to test and confirm the fix.

**Pull request merged**
